### ISSUE TITLE
PIN-OUT abbreviations are unclear, confusing and NON-standard

### ISSUE THREAD

**Issue by StefanL38** [pinout-xyz/picopins#4]
Hi everybody,

The abbreviations in the pinout of the datasheet of the RaspBerry Pi pico like found here
https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf

are

- unclear
- confusing
- NON-standard

They are neither the old common abbreviations MISO/MOSI nor are they following the new standard as described here
https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names/
This is a screenshot of the used pinout in the datasheet
![image](https://github.com/pinout-xyz/picopins/assets/8948220/8f14d123-88c1-49d2-a742-dc9a0593ec88)

As you can see the SPI-interface pins are named SPI0    which could be seen not as SPI-0 but easily could be seen as SPIO
then it is using additionally Rx/Tx which is **very uncommon** 

Rx / Tx give some hints but still says nothing about the role the pico is playing. As a microcontroller that communicates with another microcontroller it could well be that this particular one has the role of the **slave**

So what would be so hard about changing these abbreviations to follow the new standard of naming them
![image](https://github.com/pinout-xyz/picopins/assets/8948220/7341fa35-898e-4766-aa56-83fdb348a5cf)

best regards Stefan

**Comment by Gadgetoid** [comment]
I don't have anything to do with writing or maintaining the linked datasheet, nor any affiliation with Raspberry Pi, nor any ability to influence their choices of nomenclature.

To be fair, though, rocking up here and giving a totally unaffiliated person an ear bashing is roughly exactly as likely to be successful as asking Raspberry Pi to change something.

Good luck with that!

(I'd say there's a really, really good reason they didn't decide to put PICO all over their Pico datasheet 🤦which leaves SDO and SDI, which are no better than TX and RX- terms that have enjoyed roughly (at a wild guess) a century of popular usage originating in telecommunications)

**Comment by lurch** [comment]
FYI the **correct** place to report problems with https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf is https://github.com/raspberrypi/pico-feedback

But before you do that, you might want to read https://github.com/raspberrypi/pico-feedback/issues/45 and https://github.com/raspberrypi/pico-feedback/issues/192
